"""Added tricks model

Revision ID: fb30087cc1e1
Revises: aaae751e092a
Create Date: 2023-05-18 15:00:05.102568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb30087cc1e1'
down_revision = 'aaae751e092a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tricks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steeze', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['scores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tricks')
    # ### end Alembic commands ###
